title: 张诚琪 | 个人主页
description: 中国科学技术大学 计算数学 本科在读
author: 张诚琪
email: zcq003715@mail.ustc.edu.cn

url: "https://zhang-chengqi.github.io"
baseurl: "/My_Homepage"

permalink: /posts/:title.html

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

navigation:
  - title: Blog
    url: /My_Homepage/blog.html
  - title: Writing
    url: /My_Homepage/#writing
  - title: Publications
    url: /My_Homepage/#publications
  - title: Projects
    url: /My_Homepage/#projects
  - title: Contact
    url: /My_Homepage/#contact